name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: build
        run: npm install
        
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/integration/form.feature
