
name: Run tests

on: 
  push:
    branches: [main] #Branch que irá disparar o CI

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
        
    # instalacao das dependências
    - run: npm install
    
    # execucao dos testes
    - run: npx cypress run
