
name: Run tests

on: 
  push:
    branches: [main] #Branch que irá disparar o CI
   
jobs:
  cypress-run:
    runs-on: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1 # Verifica o repositório e baixa o código
      - name: Installing dependencies and running cypress;
        uses: cypress-io/github-action@v2 # Já executa o teste não tendo que passar pra subir o cypress
        with:
          start: npm install
